import type { Vehicle } from "@/lib/vehicles"

import { EXPORT_OWNER, FIRST_OWNER } from "./people"

export const CLEAN_VIN = "4JGFB8KBXPA812634"
export const CLONED_VIN = "5TDEBRCH9SS041927"
export const EXPORTED_VIN = "SALWR2SEXNA209311"
/** Registered in Ontario while the same VIN holds an active Pennsylvania title. */
export const US_TITLE_VIN = "JTJTABGX9R4027418"
/**
 * Catch 4, the border: clean in every record, declared for export at the Port of
 * Montréal under its owner's name, and the owner never agreed (2026-09-30 call).
 */
export const EXPORT_VIN = "1C6SRFHT4RN318405"
/** Brand new: decodes, but has no registration until a dealer submits one. */
export const NEW_VIN = "4JGFF5KE3SB412009"

export const DEMO_VEHICLES: Vehicle[] = [
  {
    vin: CLEAN_VIN,
    year: 2023,
    make: "Mercedes-AMG",
    model: "GLE 63 S",
    trim: "4MATIC+",
    colour: "Obsidian Black",
    bodyStyle: "SUV",
    plate: "CKXR 214",
    registeredOn: "2023-04-18",
    odometer: 31240,
    owner: {
      name: "Daniel Okafor",
      phone: "(416) 555-0917",
      phoneLast4: "0917",
      city: "Toronto, ON",
    },
    lastInspection: "2025-04-11",
    riskTier: "high-value",
    records: {
      stolenReport: null,
      writeOff: null,
      collision: null,
      duplicateIdentity: null,
      usTitle: null,
      otherJurisdiction: null,
      brand: null,
      lien: null,
    },
    decoded: {
      year: 2023,
      make: "Mercedes-AMG",
      model: "GLE 63 S",
      bodyStyle: "SUV",
      plant: "Tuscaloosa, Alabama, USA",
    },
    history: [
      {
        kind: "import",
        date: "2023-02-27",
        agency: "Transport Canada",
        port: "Windsor, ON",
        from: "United States",
        detail: "Registrar of Imported Vehicles · new vehicle",
      },
      { kind: "customsEntry", date: "2023-02-27", agency: "CBSA", port: "Windsor, ON" },
      { kind: "firstRegistration", date: "2023-04-18", agency: "MTO", office: "4412 · Toronto" },
      {
        kind: "odometer",
        date: "2023-04-18",
        agency: "Dealer",
        reading: 42,
        source: "Dealer delivery",
      },
      {
        kind: "odometer",
        date: "2024-05-02",
        agency: "Dealer",
        reading: 14880,
        source: "Service record",
      },
      { kind: "renewal", date: "2025-04-11", agency: "MTO", office: "4412 · Toronto" },
      {
        kind: "odometer",
        date: "2025-04-11",
        agency: "MTO",
        reading: 31240,
        source: "Registration renewal",
      },
    ],
  },
  {
    vin: CLONED_VIN,
    year: 2025,
    make: "Toyota",
    model: "Highlander",
    trim: "Platinum",
    colour: "Wind Chill Pearl",
    bodyStyle: "SUV",
    plate: "BWTP 903",
    registeredOn: "2025-02-03",
    odometer: 8410,
    owner: {
      name: "Priya Raghunathan",
      phone: "(905) 555-5528",
      phoneLast4: "5528",
      city: "Whitby, ON",
    },
    lastInspection: "2025-08-20",
    riskTier: "high-value",
    records: {
      stolenReport: null,
      writeOff: {
        insurer: "Aviva Canada",
        declaredOn: "2025-06-14",
        reason: "Total loss following collision",
      },
      collision: {
        occurredOn: "2025-06-12",
        location: "Hwy 401 near Whitby, ON",
        severity: "Severe, airbags deployed",
      },
      duplicateIdentity: {
        plate: "CRHM 118",
        since: "2025-08-20",
      },
      usTitle: null,
      otherJurisdiction: null,
      brand: null,
      lien: null,
    },
    decoded: {
      year: 2025,
      make: "Toyota",
      model: "Highlander",
      bodyStyle: "SUV",
      plant: "Princeton, Indiana, USA",
    },
    history: [
      {
        kind: "import",
        date: "2025-01-16",
        agency: "Transport Canada",
        port: "Sarnia, ON",
        from: "United States",
        detail: "Registrar of Imported Vehicles · new vehicle",
      },
      { kind: "customsEntry", date: "2025-01-16", agency: "CBSA", port: "Sarnia, ON" },
      { kind: "firstRegistration", date: "2025-02-03", agency: "MTO", office: "4603 · Whitby" },
      {
        kind: "odometer",
        date: "2025-02-03",
        agency: "Dealer",
        reading: 12,
        source: "Dealer delivery",
      },
      {
        kind: "odometer",
        date: "2025-06-12",
        agency: "Insurer",
        reading: 6200,
        source: "Collision report",
      },
      { kind: "transfer", date: "2025-08-20", agency: "MTO", office: "4419 · Scarborough" },
      {
        kind: "odometer",
        date: "2025-08-20",
        agency: "MTO",
        reading: 8410,
        source: "Registration",
      },
    ],
  },
  {
    vin: EXPORTED_VIN,
    year: 2022,
    make: "Land Rover",
    model: "Range Rover Sport",
    trim: "HSE Dynamic",
    colour: "Santorini Black",
    bodyStyle: "SUV",
    plate: "CPLR 482",
    registeredOn: "2022-01-14",
    odometer: 47310,
    owner: {
      name: "Amara Chen",
      phone: "(905) 555-2286",
      phoneLast4: "2286",
      city: "Mississauga, ON",
    },
    lastInspection: "2025-01-09",
    riskTier: "high-value",
    records: {
      stolenReport: null,
      writeOff: null,
      collision: null,
      duplicateIdentity: null,
      usTitle: null,
      otherJurisdiction: null,
      brand: null,
      lien: null,
    },
    decoded: {
      year: 2022,
      make: "Land Rover",
      model: "Range Rover Sport",
      bodyStyle: "SUV",
      plant: "Solihull, England, UK",
    },
    history: [
      {
        kind: "import",
        date: "2021-11-22",
        agency: "Transport Canada",
        port: "Halifax, NS",
        from: "United Kingdom",
        detail: "Registrar of Imported Vehicles · new vehicle",
      },
      { kind: "customsEntry", date: "2021-11-22", agency: "CBSA", port: "Halifax, NS" },
      {
        kind: "firstRegistration",
        date: "2022-01-14",
        agency: "MTO",
        office: "4507 · Mississauga",
      },
      {
        kind: "odometer",
        date: "2022-01-14",
        agency: "Dealer",
        reading: 28,
        source: "Dealer delivery",
      },
      {
        kind: "odometer",
        date: "2023-01-10",
        agency: "Dealer",
        reading: 19640,
        source: "Service record",
      },
      { kind: "renewal", date: "2024-01-11", agency: "MTO", office: "4507 · Mississauga" },
      {
        kind: "odometer",
        date: "2024-01-11",
        agency: "MTO",
        reading: 33970,
        source: "Registration renewal",
      },
      { kind: "renewal", date: "2025-01-09", agency: "MTO", office: "4507 · Mississauga" },
      {
        kind: "odometer",
        date: "2025-01-09",
        agency: "MTO",
        reading: 47310,
        source: "Registration renewal",
      },
      {
        kind: "export",
        date: "2025-03-18",
        agency: "CBSA",
        port: "Port of Montréal, QC",
      },
    ],
  },
  {
    vin: US_TITLE_VIN,
    year: 2024,
    make: "Lexus",
    model: "GX 550",
    trim: "Overtrail+",
    colour: "Earth",
    bodyStyle: "SUV",
    plate: "CTRV 657",
    registeredOn: "2024-05-09",
    odometer: 22860,
    owner: {
      name: "Marc-André Gagnon",
      phone: "(905) 555-7731",
      phoneLast4: "7731",
      city: "Vaughan, ON",
    },
    lastInspection: "2025-05-06",
    riskTier: "high-value",
    records: {
      stolenReport: null,
      writeOff: null,
      collision: null,
      duplicateIdentity: null,
      usTitle: { state: "Pennsylvania", issuedOn: "2025-07-22" },
      otherJurisdiction: null,
      brand: null,
      lien: null,
    },
    decoded: {
      year: 2024,
      make: "Lexus",
      model: "GX 550",
      bodyStyle: "SUV",
      plant: "Tahara, Aichi, Japan",
    },
    history: [
      {
        kind: "import",
        date: "2024-04-02",
        agency: "Transport Canada",
        port: "Port of Vancouver, BC",
        from: "Japan",
        detail: "Registrar of Imported Vehicles · new vehicle",
      },
      { kind: "customsEntry", date: "2024-04-02", agency: "CBSA", port: "Port of Vancouver, BC" },
      { kind: "firstRegistration", date: "2024-05-09", agency: "MTO", office: "4588 · Vaughan" },
      {
        kind: "odometer",
        date: "2024-05-09",
        agency: "Dealer",
        reading: 18,
        source: "Dealer delivery",
      },
      { kind: "renewal", date: "2025-05-06", agency: "MTO", office: "4588 · Vaughan" },
      {
        kind: "odometer",
        date: "2025-05-06",
        agency: "MTO",
        reading: 22860,
        source: "Registration renewal",
      },
    ],
  },
  {
    vin: EXPORT_VIN,
    year: 2024,
    make: "RAM",
    model: "1500",
    trim: "Limited",
    colour: "Diamond Black",
    bodyStyle: "Pickup",
    plate: "CPWT 318",
    registeredOn: "2024-02-09",
    odometer: 31275,
    owner: {
      name: EXPORT_OWNER.name,
      phone: EXPORT_OWNER.mobile,
      phoneLast4: EXPORT_OWNER.mobileLast4,
      city: "Oakville, ON",
    },
    lastInspection: "2026-05-12",
    riskTier: "high-value",
    records: {
      stolenReport: null,
      writeOff: null,
      collision: null,
      duplicateIdentity: null,
      usTitle: null,
      otherJurisdiction: null,
      brand: null,
      lien: null,
    },
    decoded: {
      year: 2024,
      make: "RAM",
      model: "1500",
      bodyStyle: "Pickup",
      plant: "Sterling Heights, Michigan, USA",
    },
    history: [
      {
        kind: "import",
        date: "2024-01-22",
        agency: "Transport Canada",
        port: "Windsor, ON",
        from: "United States",
        detail: "Registrar of Imported Vehicles · new vehicle",
      },
      { kind: "customsEntry", date: "2024-01-22", agency: "CBSA", port: "Windsor, ON" },
      { kind: "firstRegistration", date: "2024-02-09", agency: "MTO", office: "4436 · Brampton" },
      {
        kind: "odometer",
        date: "2024-02-09",
        agency: "Dealer",
        reading: 24,
        source: "Dealer delivery",
      },
      { kind: "transfer", date: "2025-05-14", agency: "MTO", office: "4521 · Oakville" },
      {
        kind: "odometer",
        date: "2025-05-14",
        agency: "MTO",
        reading: 18940,
        source: "Registration",
      },
      { kind: "renewal", date: "2026-05-12", agency: "MTO", office: "4521 · Oakville" },
      {
        kind: "odometer",
        date: "2026-05-12",
        agency: "MTO",
        reading: 31275,
        source: "Registration renewal",
      },
    ],
  },
  {
    vin: NEW_VIN,
    year: 2026,
    make: "Mercedes-Benz",
    model: "GLE 450",
    trim: "4MATIC",
    colour: "Obsidian Black",
    bodyStyle: "SUV",
    plate: null,
    registeredOn: null,
    odometer: 0,
    owner: {
      name: FIRST_OWNER.name,
      phone: FIRST_OWNER.mobile,
      phoneLast4: FIRST_OWNER.mobileLast4,
      city: "Toronto, ON",
    },
    lastInspection: null,
    riskTier: "high-value",
    records: {
      stolenReport: null,
      writeOff: null,
      collision: null,
      duplicateIdentity: null,
      usTitle: null,
      otherJurisdiction: null,
      brand: null,
      lien: null,
    },
    decoded: {
      year: 2026,
      make: "Mercedes-Benz",
      model: "GLE 450",
      bodyStyle: "SUV",
      plant: "Tuscaloosa, Alabama, USA",
    },
    history: [],
  },
]
